name: Update IPTV Playlist
on:
  schedule:
    - cron: '0 */6 * * *' # รันทุกๆ 6 ชั่วโมง
  workflow_dispatch:      # กดรันเองแบบ Manual ได้ด้วย

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run update script
        run: python update_links.py

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add playlist.m3u
          git commit -m "Auto-update playlist" || exit 0
          git push
